name: Pinax Lints
description: Runs flake8 and isort
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: isort
      uses: jamescurtin/isort-action@master

    - name: Lints
      uses: py-actions/flake8@v1
      with:
        args: "--config tox.ini"
